# Development configuration
app:
  name: "Italian Teacher"
  version: "0.1.0"
  debug: true
  log_level: "DEBUG"

api:
  host: "localhost"
  port: 8000
  reload: true

database:
  url: "sqlite:///./italian_teacher_dev.db"
  echo: true

redis:
  url: "redis://localhost:6379/0"

models:
  base_model: "microsoft/DialoGPT-medium"
  device: "cpu"  # Use "cuda" if available
  max_length: 512
  temperature: 0.7

agents:
  marco:
    personality: "friendly_conversationalist"
    encouragement_frequency: 0.3
  
  professoressa_rossi:
    personality: "grammar_expert" 
    correction_threshold: 0.5
  
  nonna_giulia:
    personality: "cultural_storyteller"
    story_frequency: 0.2
  
  lorenzo:
    personality: "modern_italian"
    slang_probability: 0.4

coordinator:
  max_context_length: 10
  agent_switch_threshold: 0.6
  difficulty_adjustment_rate: 0.1

training:
  batch_size: 8
  learning_rate: 0.0001
  num_epochs: 3
  save_steps: 500
  eval_steps: 100